AWSTemplateFormatVersion: '2010-09-09'
Description: A simple CloudFormation template to launch an EC2 instance

Resources:
  # EC2 Instance
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: my-key-pair  # key pair name
      ImageId: ami-090fa75af13c156b4  # Amazon Linux 2 AMI ID
      SecurityGroups:
        - Ref: MySecurityGroup  # Reference the security group defined below
      Tags:
        - Key: Name
          Value: MyEC2Instance

  # Security Group
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0  # Allow SSH from anywhere
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0  # Allow HTTP from anywhere

 